### ISSUE TITLE
Add GitHub templates for support

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/webtest#203]
Feature request. We're trying out a new feature of GitHub: issue templates.

See examples:
https://github.com/Pylons/docs-style-guide/issues/new/choose

Source:
https://github.com/Pylons/docs-style-guide/tree/master/.github/ISSUE_TEMPLATE

Hopefully they direct requests for support to the proper channel instead of the mere 20 people watching this repo. Please let me know your thoughts.

**Comment by gawel** [comment]
Seems nice

**Comment by stevepiercy** [comment]
Please let me know which ones you would like, and I'll submit a PR. If you choose only one, then that removes the choose one of N step.

**Comment by gawel** [comment]
Choose the easiest solution to maintain. I'm fine with all of them. If it's easier to have only one then bug report should be enough.

**Comment by stevepiercy** [comment]
I just realized, there's no contributing.md, CONTRIBUTORS.txt, COPYRIGHT.txt, or LICENSE.txt. Should I port those over from Pyramid and adapt them for webtest as well?

I don't know what we can do about the lack of CONTRIBUTORS.txt to date.

**Comment by gawel** [comment]
Yes please!

There's the contributors list: https://github.com/Pylons/webtest/graphs/contributors
Not sure we can do something with that. Maybe if it's available via the api.

**Comment by stevepiercy** [comment]
I don't think we can use GitHub's contributor graph as a substitute for a signature in contributors. As I understand it, it is only a valid signature when the user makes their own commit in contributors by adding their own name. We cannot sign their names on their behalf. I don't know what to do next, other than ask for advice from @tseaver.

I'll work on the other items.

**Comment by mmerickel** [comment]
webob and webtest were inherited from elsewhere and there is no real point in adding a CONTRIBUTORS.txt to them as it would be virtually impossible at this point to track down all the contributors and get them to sign. It should have an MIT LICENSE.txt file though.

**Comment by tseaver** [comment]
WebOb has a [`docs/license.txt`](https://github.com/Pylons/webob/blob/master/docs/license.txt) file, which has a copyright statement:

> Copyright (c) 2007 Ian Bicking and Contributors

and the MIT license text.  This is essentially unchanged since its original [0.8 release sdist](https://files.pythonhosted.org/packages/77/e9/852a66d4c59428451d6006592428906c326ee7fe38cc223ff08cb2f70755/WebOb-0.8.tar.gz).

Webtest has a [`docs/license.rst`](https://github.com/Pylons/webtest/blob/master/docs/license.rst) with copyright statement:

> Copyright (c) 2010 Ian Bicking and Contributors

and the MIT license text.  It is likewise substantially unchanged from the original [0.9 release sdist](https://files.pythonhosted.org/packages/d7/12/0a0aee4b218a42997b2002d3c32df31ac6e974fc343504addff1d7692e54/WebTest-0.9.tar.gz) (the copyright date there was 2007).

**Comment by stevepiercy** [comment]
According to GitHub's documentation, a license file is usually at the repo's root.

https://help.github.com/articles/licensing-a-repository/

I agree with that, making it easier to find and more likely be automatically detected by GitHub. Is there a reason not to move `license.*` to the repo root? It appears that merely including a statement in webob's readme does not assist with automatic detection.

I'll not add a `CONTRIBUTORS.txt`.

**Comment by gawel** [comment]
Merged. Thanks
